// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace admfin.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240303112234_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Models.Balancos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Balancos");
                });

            modelBuilder.Entity("Models.Itens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Models.ItensBalancos", b =>
                {
                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdBalanco")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorItem")
                        .HasColumnType("REAL");

                    b.HasKey("IdItem", "IdBalanco");

                    b.HasIndex("IdBalanco");

                    b.ToTable("ItensBalancos");
                });

            modelBuilder.Entity("Models.ItensBalancos", b =>
                {
                    b.HasOne("Models.Balancos", "Balancos")
                        .WithMany()
                        .HasForeignKey("IdBalanco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Itens", "Itens")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balancos");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
